/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.compra;

import vista.venta.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;
import controlador.ControladorProducto;

import modelo.Producto;
import modelo.Proveedor;

/**
 *
 * @author Analía Santomé
 */
public class agregarProductoCompra extends javax.swing.JDialog {
    
    private TableRowSorter trsFiltro;
    Integer cantidad;
    Double costo;
    Long codigoSeleccionado;
    ControladorProducto ctrpro = new ControladorProducto();
    Producto P = new Producto();
    Proveedor prov = new Proveedor();
    
    /**
     * Creates new form agregarProductoVenta
     */
    public agregarProductoCompra(java.awt.Frame parent, boolean modal,Proveedor proveedor) throws Exception {
        super(parent, modal);
        this.prov = proveedor;
        initComponents();
        setLocationRelativeTo(null);
        formWindowOpened();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListado);

        jLabel1.setText("Filtrar por");

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nombre", "Descripcion" }));

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSalir)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregar, botonSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregar, botonSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        txtFiltro.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaListado.getModel());
        tablaListado.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtFiltroKeyTyped
    private void agregarProducto(Long codigo){
        try{
        costo = Double.parseDouble(JOptionPane.showInputDialog("Costo?"));
            Producto aux = ctrpro.buscar(Producto.class, codigoSeleccionado);
           
            if(aux.getVieneEnCaja()){
                cantidad= Integer.parseInt(JOptionPane.showInputDialog("Cantidad de cajas?"));
                if(aux.getStockActual() + (cantidad*aux.getCantidadPorCaja()) > aux.getStockMaximo()){
                    int respuesta=JOptionPane.showConfirmDialog(this,
                            "Con esta compra se superará el stock maximo, ¿desea cambiar la cantidad" +
                            " pedida a "+ (aux.getStockMaximo()-aux.getStockActual())/aux.getCantidadPorCaja() + " cajas para"+
                            " completar al maximo?",
                            "Advertencia!",
                            JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION){
                        cantidad = (aux.getStockMaximo()-aux.getStockActual());
                        }else{
                       return; 
                    }
                
                }
                
            }else{
                cantidad= Integer.parseInt(JOptionPane.showInputDialog("Cantidad?"));
                if((aux.getStockActual()+ cantidad) > aux.getStockMaximo()){
                int respuesta=JOptionPane.showConfirmDialog(this,
                        "Con esta compra se superará el stock maximo, ¿desea cambiar la cantidad" +
                        " pedida a "+ (aux.getStockMaximo()-aux.getStockActual()) + " unidades para"+
                        " completar al maximo?",
                        "Advertencia!",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    cantidad = (aux.getStockMaximo()-aux.getStockActual());
                    }else{
                   return; 
                }
                
            }
            }
           
            P=aux;      
             
            super.dispose();
        } catch (Exception ex) {
            Logger.getLogger(agregarProductoCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        //try {
            int target=tablaListado.getSelectedRow();
            codigoSeleccionado= (Long)tablaListado.getValueAt(target, 0);
            agregarProducto(codigoSeleccionado);
            /*costo = Double.parseDouble(JOptionPane.showInputDialog("Costo?"));
            Producto aux = ctrpro.buscar(Producto.class, codigoSeleccionado);
           
            if(aux.getVieneEnCaja()){
                cantidad= Integer.parseInt(JOptionPane.showInputDialog("Cantidad de cajas?"));
                if(aux.getStockActual() + (cantidad*aux.getCantidadPorCaja()) > aux.getStockMaximo()){
                    int respuesta=JOptionPane.showConfirmDialog(this,
                            "Con esta compra se superará el stock maximo, ¿desea cambiar la cantidad" +
                            " pedida a "+ (aux.getStockMaximo()-aux.getStockActual())/aux.getCantidadPorCaja() + " cajas para"+
                            " completar al maximo?",
                            "Advertencia!",
                            JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION){
                        cantidad = (aux.getStockMaximo()-aux.getStockActual());
                        }else{
                       return; 
                    }
                
            }
                
            }else{
                cantidad= Integer.parseInt(JOptionPane.showInputDialog("Cantidad?"));
                if((aux.getStockActual()+ cantidad) > aux.getStockMaximo()){
                int respuesta=JOptionPane.showConfirmDialog(this,
                        "Con esta compra se superará el stock maximo, ¿desea cambiar la cantidad" +
                        " pedida a "+ (aux.getStockMaximo()-aux.getStockActual()) + " unidades para"+
                        " completar al maximo?",
                        "Advertencia!",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    cantidad = (aux.getStockMaximo()-aux.getStockActual());
                    }else{
                   return; 
                }
                
            }
            }
           
            P=aux;      
             
            super.dispose();
        } catch (Exception ex) {
            Logger.getLogger(agregarProductoCompra.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        super.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void tablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()){
            int target=tablaListado.getSelectedRow();
            codigoSeleccionado= (Long)tablaListado.getValueAt(target, 0);
            agregarProducto(codigoSeleccionado);
        }
    }//GEN-LAST:event_tablaListadoMouseClicked
    private void formWindowOpened() throws Exception {                                  
        DefaultTableModel model = (DefaultTableModel) tablaListado.getModel();
        Object rowData[] = new Object[3];
        
        for(Producto c : ctrpro.buscarConConsultaNombrada("Producto.findProductos")){
           if(c.getProveedores().contains(prov) || prov.getNombre_comercial().equals("COMPRA LIBRE")){
               rowData[0] = c.getCodigoProducto();
               rowData[1] = c.getNombre();
               rowData[2] = c.getDescripcion();       
               model.addRow(rowData);
            }
       tablaListado.setModel(model);
   
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarProductoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    agregarProductoCompra dialog = new agregarProductoCompra(new javax.swing.JFrame(), true,null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(agregarProductoCompra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListado;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

public void filtro() {
        int columnaABuscar = 0;
        if (comboFiltro.getSelectedItem() == "Codigo") {
            columnaABuscar = 0;
        }
        if (comboFiltro.getSelectedItem().toString().equals("Nombre")) {
            columnaABuscar = 1;
        }
        if (comboFiltro.getSelectedItem() == "Descripcion") {
            columnaABuscar = 2;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(), columnaABuscar));
    }

    public Integer getCantidad() {
        return cantidad;
    }
    public Long getCodigoSeleccionado() {
        return codigoSeleccionado;
    }

    public Producto getP() {
        return P;
    }
    public Double getCosto() {
        return costo;
    }

    public Proveedor getProv() {
        return prov;
    }

    public void setProv(Proveedor prov) {
        this.prov = prov;
    }
    
    


}
