/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.compra;

import vista.venta.*;
import controlador.ControladorCliente;
import controlador.ControladorProducto;
import controlador.ControladorCompra;
import controlador.ControladorLineaTransaccion;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Compra;
import modelo.Proveedor;
import modelo.CuentaCorriente;
import modelo.LineaTransaccion;

/**
 *
 * @author Analía Santomé
 */
public class NuevaCompra extends javax.swing.JFrame {
    List <Producto> productos_a_cargar=new ArrayList<>();
    ControladorCompra ctrcom = new ControladorCompra();
    ControladorProducto ctrpro = new ControladorProducto();
    ControladorCliente ctrcli = new ControladorCliente();
    ControladorLineaTransaccion ctrltr = new ControladorLineaTransaccion();
    Proveedor P = null;//new Proveedor();
    /**
     * Creates new form NuevaCompra
     * @throws java.lang.Exception
     */
    public NuevaCompra() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoProveedor = new javax.swing.JTextField();
        botonBuscarCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        boxFecha = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTipoFactura = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosCompra = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        botonImprimir = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonGuardarVenta = new javax.swing.JButton();
        botonAgregarProducto = new javax.swing.JButton();
        botonEliminarSeleccionados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva venta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Total  $");

        campoTotal.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
            .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Proveedor");

        campoProveedor.setEditable(false);
        campoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProveedorActionPerformed(evt);
            }
        });

        botonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscarChico.png"))); // NOI18N
        botonBuscarCliente.setBorder(null);
        botonBuscarCliente.setBorderPainted(false);
        botonBuscarCliente.setContentAreaFilled(false);
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha");

        boxFecha.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarCliente)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarCliente)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(boxFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonBuscarCliente, campoProveedor});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Numero factura");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tipo factura");

        campoTipoFactura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        campoTipoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(campoTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(campoTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaProductosCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Ultimo costo", "Nuevo costo", "Cantidad", "Precio total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductosCompra);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/imprimir.png"))); // NOI18N
        botonImprimir.setContentAreaFilled(false);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/salir.png"))); // NOI18N
        botonSalir.setContentAreaFilled(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonGuardarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/guardar.png"))); // NOI18N
        botonGuardarVenta.setContentAreaFilled(false);
        botonGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardarVenta)
                    .addComponent(botonImprimir)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonGuardarVenta, botonImprimir, botonSalir});

        botonAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar50X50.png"))); // NOI18N
        botonAgregarProducto.setBorder(null);
        botonAgregarProducto.setBorderPainted(false);
        botonAgregarProducto.setContentAreaFilled(false);
        botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductoActionPerformed(evt);
            }
        });

        botonEliminarSeleccionados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/borrar50X50.png"))); // NOI18N
        botonEliminarSeleccionados.setContentAreaFilled(false);
        botonEliminarSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSeleccionadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botonEliminarSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAgregarProducto)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarProducto)
                    .addComponent(botonEliminarSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProveedorActionPerformed
        
    }//GEN-LAST:event_campoProveedorActionPerformed
    private void mostrarCartelError(Component padre,String error){
        JOptionPane.showMessageDialog(padre,
                       error,
                       "Error!",
                        JOptionPane.INFORMATION_MESSAGE);
    }
    private void botonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarVentaActionPerformed
        Compra nueva=new Compra();
        try{
            
            nueva.setFecha(boxFecha.getDate());
            if(P==null){
                JOptionPane.showMessageDialog(this,
                       "Por favor seleccione un proveedor!",
                       "Error!",
                        JOptionPane.ERROR_MESSAGE);
            }else{
            nueva.setProveedor(P);
            }
            nueva.setTotal(Double.parseDouble(campoTotal.getText()));

            //nueva.setProductos(productos_a_cargar);

            nueva.setNumero_factura(numeroFactura.getText());
            String tipoFactura = (String)campoTipoFactura.getSelectedItem();
            nueva.setTipo_factura(tipoFactura.charAt(0));
        }catch(Exception e){
            mostrarCartelError(this,"Ocurrio un error en la carga de algun dato");
        }
        
        for(int i=0;i<tablaProductosCompra.getRowCount();i++){
            Integer cant_a_sumar= (Integer)tablaProductosCompra.getValueAt(i, 5);
            Long codigo= (Long)tablaProductosCompra.getValueAt(i, 0);
            for(Producto P:this.productos_a_cargar){
                if(P.getCodigoProducto().equals(codigo)){
                         P.aumentarStock(cant_a_sumar);
                        //P.setStockActual(P.getStockActual()+cant_a_sumar);
                    try {
                        ctrpro.actualizar(P);
                    } catch (Exception e) {
                        e.printStackTrace();
                        mostrarCartelError(this,"Ocurrio un error al actualizar el stock");
                        
                    }
                    }
            }
            
        }
       
        //nueva.setProductos(productos_a_cargar);
        try{
            ctrcom.crear(nueva);
            for(int i=0;i<tablaProductosCompra.getRowCount();i++){
                LineaTransaccion nuevaLinea = new LineaTransaccion();
                nuevaLinea.setIdProducto((Long)tablaProductosCompra.getValueAt(i, 0));
                nuevaLinea.setNombreProducto((String)tablaProductosCompra.getValueAt(i, 1));
                nuevaLinea.setDescripcionProducto((String)tablaProductosCompra.getValueAt(i, 2));
                nuevaLinea.setUltimoCosto((Double)tablaProductosCompra.getValueAt(i, 3));
                nuevaLinea.setNuevoCosto((Double)tablaProductosCompra.getValueAt(i, 4));
                nuevaLinea.setCantidad((Integer)tablaProductosCompra.getValueAt(i, 5));
                nuevaLinea.setTotal((Double)tablaProductosCompra.getValueAt(i,  6));
                //nuevaLinea.setTransaccionPadre(nueva);
                ctrltr.crear(nuevaLinea);
                nueva.agregarLinea(nuevaLinea); 
            }
        }catch(Exception e){
            e.printStackTrace();
            mostrarCartelError(this,"Ocurrio un error al cargar las lineas");
            
        }
        try {
            ctrcom.actualizar(nueva);
            int respuesta=JOptionPane.showConfirmDialog(this,
                        "Se registro correctamente la compra" +
                        "¿Desea registrar otra?",
                        "Exito",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    limpiarCampos();
                        
                    }else{
                   super.dispose(); 
                }
        } catch (Exception e) {
            e.printStackTrace();
            mostrarCartelError(this,"Ocurrio un error al registrar la compra");
            
        }
        
       
    }//GEN-LAST:event_botonGuardarVentaActionPerformed

    private void botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductoActionPerformed
        try {
            if(this.P==null){
                mostrarCartelError(this,"Primero debe seleccionar un proveedor!");
            }else{
            agregarProductoCompra apv = new agregarProductoCompra(this, rootPaneCheckingEnabled,P);
            apv.setVisible(rootPaneCheckingEnabled);
            Integer cantidad_producto=apv.getCantidad();
            Double costo_producto=apv.getCosto();
            Long codigo_buscado=apv.getCodigoSeleccionado();
            
            DefaultTableModel model = (DefaultTableModel) tablaProductosCompra.getModel();
            Object rowData[] = new Object[7];
            
            //Producto c = ctrpro.buscar(Producto.class, codigo_buscado);
            
            Producto c = apv.getP();
            
            this.productos_a_cargar.add(c);
            
            rowData[0] = c.getCodigoProducto();
            rowData[1] = c.getNombre();
            rowData[2] = c.getDescripcion();
            rowData[3] = c.getUltimoCosto();
            rowData[4] = costo_producto;
            if(c.getVieneEnCaja()){
                rowData[5] = cantidad_producto*c.getCantidadPorCaja();
            }else{
                rowData[5] = cantidad_producto;
            }
            rowData[6] = (costo_producto*cantidad_producto);
            model.addRow(rowData);
            tablaProductosCompra.setModel(model);
            
            Double total=0.0;
            for(int i=0;i<tablaProductosCompra.getRowCount();i++){
                total+= (Double)tablaProductosCompra.getValueAt(i, 6);
            }
            campoTotal.setText(String.valueOf(total));
            }
        } catch (Exception ex) {
            Logger.getLogger(NuevaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botonAgregarProductoActionPerformed

    private void limpiarCampos(){
        numeroFactura.setText("");
        campoTipoFactura.setSelectedIndex(0);
        campoProveedor.setText("");
        boxFecha.setDate(new Date());
        campoTotal.setText("");
        
        DefaultTableModel dtm =(DefaultTableModel)tablaProductosCompra.getModel();
        dtm.setRowCount(0);
        
    }
    private void botonEliminarSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSeleccionadosActionPerformed
        int target=tablaProductosCompra.getSelectedRow();
        Long codigoSeleccionado = (Long)tablaProductosCompra.getValueAt(target, 0);
        
        Iterator<Producto> iter=productos_a_cargar.iterator();
        while (iter.hasNext()) {
                Producto c = iter.next();
                if(codigoSeleccionado.equals(c.getCodigoProducto())){
                    iter.remove();
                    }
        }                
        
        System.out.println(this.productos_a_cargar.toString());
        ((DefaultTableModel)tablaProductosCompra.getModel()).removeRow(tablaProductosCompra.getSelectedRow());
    }//GEN-LAST:event_botonEliminarSeleccionadosActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this,
                        "¿Desea salir sin terminar la operacion?",
                        "Exito",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    super.dispose();
                        
                    }else{
                   return; 
                }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        try{
            agregarProveedorCompra acv = new agregarProveedorCompra(this, rootPaneCheckingEnabled);
            acv.setVisible(true);
            if(acv.getP()!=null){
                P = acv.getP();
                campoProveedor.setText(P.getCodigoProveedor()+" - "+P.getNombre_comercial());
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NuevaCompra().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NuevaCompra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonEliminarSeleccionados;
    private javax.swing.JButton botonGuardarVenta;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonSalir;
    private com.toedter.calendar.JDateChooser boxFecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoProveedor;
    private javax.swing.JComboBox<String> campoTipoFactura;
    private javax.swing.JFormattedTextField campoTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroFactura;
    private javax.swing.JTable tablaProductosCompra;
    // End of variables declaration//GEN-END:variables
}
