/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.AltaProducto;


import controlador.ControladorCategoria;

import controlador.ControladorProducto;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Categoria;

import modelo.Producto;
import modelo.Proveedor;
import controlador.ControladorProveedor;
import modelo.SistemaVenta;

/**
 *
 * @author Analía Santomé
 */
public class AltaProducto extends javax.swing.JFrame {
    ControladorCategoria ctrcat = new ControladorCategoria();
    ControladorProveedor ctrprov = new ControladorProveedor();
    ControladorProducto ctrpro = new ControladorProducto();
    List<Categoria> categoriasDisponibles = new ArrayList<>();
    List<Categoria> subCategoriasDisponibles = new ArrayList<>();
    List <Proveedor> proveedoresProducto = new ArrayList<>();
    SistemaVenta sv = SistemaVenta.getSistemaVenta();
    /**
     * Creates new form AgregarProducto
     */
    public AltaProducto() {
        
        initComponents();
        poblarCategorias();
        setLocationRelativeTo(null);
    }
    
    public void cargarCategorias(){
        try {
            categoriasDisponibles = ctrcat.buscarConConsultaNombrada("Categoria.findPrincipales");
        } catch (Exception ex) {
            Logger.getLogger(AltaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void poblarCategorias(){
        cargarCategorias();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) boxCategorias.getModel();
        modelo.removeAllElements();
        try{
        for(Categoria c : categoriasDisponibles){
            boxCategorias.addItem(c.getNombreCategoria());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public Object getCategoriaSeleccionada(){
        return boxCategorias.getSelectedItem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoMarca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        habilitadoSi = new javax.swing.JRadioButton();
        habilitadoNo = new javax.swing.JRadioButton();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        campoMinimo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoMaximo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoActual = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        campoProductosPorCaja = new javax.swing.JTextField();
        etiquetaCantidadCaja = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        boxCategorias = new javax.swing.JComboBox<>();
        boxSubcategorias = new javax.swing.JComboBox<>();
        boxProveedores = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        campoBarras = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoCodigoDeProveedor = new javax.swing.JTextField();
        labelIVA = new javax.swing.JLabel();
        comboIVA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar producto");
        setForeground(new java.awt.Color(51, 51, 255));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Marca");

        jLabel8.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Precio");

        campoPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setText("Habilitado para venta");

        buttonGroup1.add(habilitadoSi);
        habilitadoSi.setText("Si");

        buttonGroup1.add(habilitadoNo);
        habilitadoNo.setText("No");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        campoDescripcion.setColumns(20);
        campoDescripcion.setLineWrap(true);
        campoDescripcion.setRows(5);
        campoDescripcion.setMinimumSize(new java.awt.Dimension(2, 11));
        jScrollPane1.setViewportView(campoDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        jLabel9.setText("Minimo");

        jLabel13.setText("Maximo");

        jLabel10.setText("Actual");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMinimo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoActual, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoMaximo)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos por caja"));

        campoProductosPorCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoProductosPorCajaFocusLost(evt);
            }
        });

        etiquetaCantidadCaja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaCantidadCaja.setText("Cantidad por caja");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaCantidadCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoProductosPorCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoProductosPorCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCantidadCaja))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Categoria");

        jLabel6.setText("Proveedores");

        jLabel12.setText("Sub Categoria");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        boxCategorias.setModel(new javax.swing.DefaultComboBoxModel<String>());
        boxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCategoriasActionPerformed(evt);
            }
        });

        boxSubcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSubcategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(boxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxSubcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(17, 17, 17)
                .addComponent(boxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boxCategorias, boxProveedores, boxSubcategorias});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSubcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel7.setText("Codigo de barras");

        campoBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Codigo asignado por proveedor");

        campoCodigoDeProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelIVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelIVA.setText("IVA : ");

        comboIVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "27", "21", "10.5", "5" }));
        comboIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(habilitadoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(habilitadoNo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCodigoDeProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(botonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel8});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonGuardar, botonSalir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(campoCodigoDeProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(campoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(habilitadoSi)
                            .addComponent(habilitadoNo)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIVA)
                    .addComponent(comboIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonGuardar, botonSalir});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoPrecio, jLabel4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this,
                        "Esta seguro de que desea salir? ",
                        "Atencion!",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    super.dispose();
                }else{
                   return; 
                }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        
       
        try{
            
            Long codigo_barras=Long.parseLong(campoBarras.getText());
            System.out.println(codigo_barras);
            Map<String, Object> mapa = new HashMap<String,Object>();
            mapa.put("codBarra", codigo_barras);
            ControladorProducto ctrpro = new ControladorProducto();
            List<Producto> existe_barras = ctrpro.buscarConConsultaNombrada("Producto.findBarCode", mapa);
            if(!existe_barras.isEmpty()){
                    JOptionPane.showMessageDialog(this,
                        "Ya existe un producto con ese codigo de barras!",
                        "Error!",
                        JOptionPane.INFORMATION_MESSAGE);
                    campoBarras.setText("");
                    return;
                }
                
            
        }catch(Exception e){
            //if(codigo_barras==null){
            JOptionPane.showMessageDialog(this,
                    "No se ingreso un Codigo de barras para el producto",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                //campoCodigo.setText("");
                return;
        }
       
        
        Integer stock_minimo=Integer.parseInt(campoMinimo.getText());
        Integer stock_maximo=Integer.parseInt(campoMaximo.getText());
        if(stock_maximo<=stock_minimo){
            JOptionPane.showMessageDialog(this,
                    "El stock maximo no puede ser menor que el minimo",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        if(campoDescripcion.getText().isEmpty() || campoMarca.getText().isEmpty()
                    || campoPrecio.getText().isEmpty() || campoNombre.getText().isEmpty() 
                        || boxCategorias.getSelectedItem()==null || boxCategorias.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this,
                    "Se omitio uno o varios valores necesarios",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                //campoCodigo.setText("");
                return;
        }
        
        Producto P = new Producto();
        //P.setCodigoProducto(Long.parseLong(campoCodigo.getText()));
        P.setCodigoBarras(Long.parseLong(campoBarras.getText()));
        
        for(Categoria c : categoriasDisponibles){
                if(c.getNombreCategoria().equals((String)boxCategorias.getSelectedItem())){
                    P.setCategoria(c);
                }
        }
        for(Categoria c : subCategoriasDisponibles){
                if(c.getNombreCategoria().equals((String)boxSubcategorias.getSelectedItem())){
                    P.setSubCategoria(c);
                }
        }
        
        if(!campoProductosPorCaja.getText().isEmpty()){      
            P.setCantidadPorCaja(Integer.parseInt(campoProductosPorCaja.getText()));
            P.setVieneEnCaja(true);
        }
        P.setDescripcion(campoDescripcion.getText());
        Boolean habilitado = habilitadoSi.isSelected();
        P.setHabilitadoVenta(habilitado);
        P.setMarca(campoMarca.getText());
        P.setPrecioVenta(Double.parseDouble(campoPrecio.getText()));
        P.setNombre(campoNombre.getText());
        P.setStockMinimo(Integer.parseInt(campoMinimo.getText()));
        
        P.setStockActual(Integer.parseInt(campoActual.getText()));
        P.setStockMaximo(Integer.parseInt(campoMaximo.getText()));
        
        P.setCodigoDeProveedor(campoCodigoDeProveedor.getText());
        P.setValorIva(fijarNumero((Float.parseFloat(comboIVA.getSelectedItem().toString()))/100, 3));
        P.setPrecioVenta((double)fijarNumero(Float.parseFloat(campoPrecio.getText().trim()),2));
        //TERMINA LA CARGA DE LOS PRODUCTOS
        try {
            //LO AGREGAMOS A LA LIBRERIA
            P.setProveedores(this.proveedoresProducto);
            
            ctrpro.crear(P);
            
            /*Map<String, Object> mapa = new HashMap<String,Object>();
            mapa.put("codBarra", P.getCodigoBarras());
            
            List<Producto> existe_barras = ctrpro.buscarConConsultaNombrada("Producto.findBarCode", mapa);
            Producto p1 = existe_barras.get(0);
            p1.setProveedores(proveedoresParaProducto);
            ctrpro.actualizar(p1);*/
            
            
            /*for(Proveedor prov : proveedoresParaProducto){
            P.agregarProveedor(prov);
            }*/
            //Producto actualizar = ctrpro.actualizar(P);
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        /*try{
            
        }catch(Exception e){
            e.printStackTrace();
        }*/
        
        sv.addArticulo(P);
        sv.guardarDatos();
        int respuesta=JOptionPane.showConfirmDialog(this,
                        "Se guardo correctamente el producto, su codigo es: " + P.getCodigoProducto()+"\n"+
                        "¿Desea registrar otro?",
                        "Exito",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    //campoCodigo.setText("");
                    campoBarras.setText("");
                    campoNombre.setText("");
                    campoMarca.setText("");
                    campoMinimo.setText("");
                    campoMaximo.setText("");
                    campoActual.setText("");
                    campoDescripcion.setText("");
                    campoProductosPorCaja.setText("");
                    campoPrecio.setText("");
                    cargarCategorias();
                }else{
                   super.dispose(); 
                }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            AgregarProveedorAProducto ap=new AgregarProveedorAProducto(this, rootPaneCheckingEnabled);
            ap.setVisible(rootPaneCheckingEnabled);
            proveedoresProducto = ap.getProveedoresSeleccionados();
            //List <Proveedor> proveedoresProducto = ap.getProveedoresSeleccionados();
            for(Proveedor p : proveedoresProducto){
                boxProveedores.addItem(p.getNombre_comercial());
            }
            
            boxProveedores.repaint();
        } catch (Exception ex) {
            Logger.getLogger(AltaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCategoriasActionPerformed
        try {
            
            String nombreCategoriaPrincipal = (String)boxCategorias.getSelectedItem();
            
            Map<String, Object> mapa = new HashMap<>();
            mapa.put("nombreCategoriaPrincipal", nombreCategoriaPrincipal);
            
            List<Categoria> categoriaBuscada = ctrcat.buscarConConsultaNombrada("Categoria.findPorNombre", mapa);
            Categoria c = categoriaBuscada.get(0);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) boxSubcategorias.getModel();
            modelo.removeAllElements();
            subCategoriasDisponibles = c.getSubCategorias();
            for(Categoria cat : c.getSubCategorias()){
                boxSubcategorias.addItem(cat.getNombreCategoria());
            }
            
            //boxSubcategorias.repaint();
        } catch (Exception ex) {
            Logger.getLogger(AltaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_boxCategoriasActionPerformed

    private void boxSubcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSubcategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSubcategoriasActionPerformed

    private void campoProductosPorCajaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoProductosPorCajaFocusLost
       String cantidadPorCaja = campoProductosPorCaja.getText();
        if(!cantidadPorCaja.isEmpty()){
            try{
            ingresoIncorrectoNumero(Integer.parseInt(cantidadPorCaja),"Numero de la calle",null);
            }catch(Exception e){
                ingresoStringEnCampoNumerico(etiquetaCantidadCaja.getText());
            }
        }
    }//GEN-LAST:event_campoProductosPorCajaFocusLost

    private void comboIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIVAActionPerformed
    public void ingresoIncorrectoNumero (Integer valorCampo,String nombreCulpable,Long valorCampo2){
        
        try{
        //Integer piso = Integer.parseInt(campo.getText());
            if(valorCampo!=null && valorCampo<0 || valorCampo2!=null && valorCampo2<0){
               JOptionPane.showMessageDialog(this,
                       "Valor incorrecto para el campo '"+nombreCulpable+"'",
                       "Error!",
                        JOptionPane.INFORMATION_MESSAGE);
                       return;
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,
                   "Solo se aceptan numeros enteros en el campo '"+nombreCulpable+"'",
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   return;
       }
    }
    private void ingresoStringEnCampoNumerico(String nombreCampo) {
        JOptionPane.showMessageDialog(this,
                   "Solo se aceptan caracteres numericos en el campo "+nombreCampo,
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   return;
    }
    private static float fijarNumero(float numero, int digitos) {
        float resultado;
        resultado = (float) (numero * Math.pow(10, digitos));
        resultado = Math.round(resultado);
        resultado = (float) (resultado/Math.pow(10, digitos));
        return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> boxCategorias;
    private javax.swing.JComboBox<String> boxProveedores;
    private javax.swing.JComboBox<String> boxSubcategorias;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoActual;
    private javax.swing.JTextField campoBarras;
    private javax.swing.JTextField campoCodigoDeProveedor;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoMaximo;
    private javax.swing.JTextField campoMinimo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrecio;
    private javax.swing.JTextField campoProductosPorCaja;
    private javax.swing.JComboBox<String> comboIVA;
    private javax.swing.JLabel etiquetaCantidadCaja;
    private javax.swing.JRadioButton habilitadoNo;
    private javax.swing.JRadioButton habilitadoSi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIVA;
    // End of variables declaration//GEN-END:variables
}
