/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.login;

import javax.swing.JOptionPane;
import controlador.ControladorUsuario;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Usuario;
/**
 *
 * @author Analía Santomé
 */
public class VentanaPrimerIngreso extends javax.swing.JDialog {
    ControladorUsuario ctrusu = new ControladorUsuario();
    List<Usuario> usuariosRegistrados;
    Usuario usuarioLogueado;
    int codigoSalida = 0;
    /**
     * Creates new form NuevoUsuario
     */
    public VentanaPrimerIngreso(java.awt.Frame parent, boolean modal,Usuario nuevo) {
        super(parent, modal);
        try {
            usuariosRegistrados = ctrusu.buscarConConsultaNombrada("Usuario.findAll");
            this.usuarioLogueado = nuevo;
            initComponents();
            setLocationRelativeTo(null);
            JOptionPane.showMessageDialog(this,
                       "Por motivos de seguridad debe cambiar la contraseña que le brindo el administrador",
                       "Atencion",
                        JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoPassNueva = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        campoConfirmarPassNueva = new javax.swing.JPasswordField();
        campoPassActual = new javax.swing.JPasswordField();
        botonCargarUsuario = new javax.swing.JButton();

        setUndecorated(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/login.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Contraseña actual");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nueva");

        campoPassNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoPassNueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPassNuevaFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Confirmar nueva");

        campoConfirmarPassNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        campoPassActual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPassActualFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoPassActual, campoPassNueva});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(campoConfirmarPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoPassActual, campoPassNueva});

        botonCargarUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonCargarUsuario.setText("Cargar");
        botonCargarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCargarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public int getCodigoSalida(){
        return codigoSalida;
    }
    private void botonCargarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarUsuarioActionPerformed
       
        if("".equals(campoPassActual.getText())){
           JOptionPane.showMessageDialog(this,
            "No se ingreso la contraseña actual",
            "Error!",
            JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(campoPassNueva.getPassword().length==0){
           JOptionPane.showMessageDialog(this,
            "Debe ingresar una nueva clave",
            "Error!",
            JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(campoConfirmarPassNueva.getPassword().length==0){
           JOptionPane.showMessageDialog(this,
            "Por favor confirme la nueva clave",
            "Error!",
            JOptionPane.ERROR_MESSAGE);
           return;
       }
        
       if(campoPassNueva.getText().equals(campoConfirmarPassNueva.getText())){
            try {
                usuarioLogueado.setPassword(campoPassNueva.getText());
                usuarioLogueado.setNuncaEntro(false);
                ctrusu.actualizar(usuarioLogueado);
                JOptionPane.showMessageDialog(this,
                    "Gracias por cambiar su clave!",
                    "Exito!",
                    JOptionPane.INFORMATION_MESSAGE);
                
                super.dispose();
                
            } catch (Exception ex) {
                Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
           JOptionPane.showMessageDialog(this,
                    "Las claves no coinciden!",
                    "Error!",
                    JOptionPane.ERROR_MESSAGE);
                return;
       }
       
    }//GEN-LAST:event_botonCargarUsuarioActionPerformed

    private void campoPassNuevaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPassNuevaFocusLost
        if(campoPassNueva.getText().equalsIgnoreCase(usuarioLogueado.getPassword())){
            JOptionPane.showMessageDialog(this,
                "La nueva contraseña no puede ser igual a la actual!",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
                campoPassActual.setText("");
                campoPassNueva.setText("");
                return;
        }
    }//GEN-LAST:event_campoPassNuevaFocusLost

    private void campoPassActualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPassActualFocusLost
        if(!campoPassActual.getText().equalsIgnoreCase(usuarioLogueado.getPassword())){
            JOptionPane.showMessageDialog(this,
                "La contraseña actual es incorrecta",
                "Error!",
                JOptionPane.ERROR_MESSAGE);
                campoPassActual.setText("");
                return;
        }
    }//GEN-LAST:event_campoPassActualFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimerIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaPrimerIngreso dialog = new VentanaPrimerIngreso(new javax.swing.JFrame(),true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarUsuario;
    private javax.swing.JPasswordField campoConfirmarPassNueva;
    private javax.swing.JPasswordField campoPassActual;
    private javax.swing.JPasswordField campoPassNueva;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
