/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.login;

import javax.swing.JOptionPane;
import controlador.ControladorUsuario;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Usuario;
/**
 *
 * @author Analía Santomé
 */
public class VentanaNuevoUsuario extends javax.swing.JDialog {
    ControladorUsuario ctrusu = new ControladorUsuario();
    List<Usuario> usuariosRegistrados;
    Usuario usuarioLogueado;
    /**
     * Creates new form NuevoUsuario
     */
    public VentanaNuevoUsuario(java.awt.Frame parent, boolean modal,Usuario logueado) {
        super(parent, modal);
        try {
            usuariosRegistrados = ctrusu.buscarConConsultaNombrada("Usuario.findAll");
            this.usuarioLogueado = logueado;
            initComponents();
            setLocationRelativeTo(null);
            
        } catch (Exception ex) {
            Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoUsuarioNuevo = new javax.swing.JTextField();
        campoContrasenaNueva = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/login.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña:");

        campoUsuarioNuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        campoContrasenaNueva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoUsuarioNuevo)
                    .addComponent(campoContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Boolean existe = false;
        if("".equals(campoUsuarioNuevo.getText())){
           JOptionPane.showMessageDialog(this,
            "No se ingreso usuario",
            "Error de acceso",
            JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(campoContrasenaNueva.getPassword().length==0){
           JOptionPane.showMessageDialog(this,
            "No se ingreso clave",
            "Error de acceso",
            JOptionPane.ERROR_MESSAGE);
           return;
       }
        
       String usuario = campoUsuarioNuevo.getText();
       for(Usuario u : usuariosRegistrados){
           if(u.getNombre().equals(usuario)){
                    JOptionPane.showMessageDialog(this,
                        "Ya existe el usuario",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                    existe = true;
                    return;
            
            }
       }
       if(!existe){
               try {
                   String passAdmin = JOptionPane.showInputDialog("Por favor reingrese la contraseña de Administrador");
                   if(usuarioLogueado.getPassword().equals(passAdmin)){
                       Usuario nuevo = new Usuario(usuario,campoContrasenaNueva.getText());
                       int respuesta=JOptionPane.showConfirmDialog(this,
                        "¿El nuevo usuario sera Administrador del Sistema?",
                        "Atencion",
                        JOptionPane.YES_NO_OPTION);
                        if(respuesta == JOptionPane.YES_OPTION){
                            nuevo.setEsAdministrador(true);
                        }else{
                           nuevo.setEsAdministrador(false);
                        }
                        
                        ctrusu.crear(nuevo);
                        JOptionPane.showMessageDialog(this,
                               "Se creo con exito el nuevo usuario",
                               "Exito",
                               JOptionPane.INFORMATION_MESSAGE);
                            super.dispose();
                   }else{
                       JOptionPane.showMessageDialog(this,
                        "Error en la autentificacion de Administrador!",
                        "Error!",
                        JOptionPane.ERROR_MESSAGE);
                       return;
                   }
                   
               } catch (Exception ex) {
                   Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(Level.SEVERE, null, ex);
               }
       }
          
       
       
       
       /*Map<String, Object> mapa = new HashMap<>();
       
       mapa.put("nombreUsuario", usuario);
       List<Usuario> usuarioBuscado;
        try {
            usuarioBuscado = ctrusu.buscarConConsultaNombrada("Usuario.findPorNombre", mapa);
            if(usuarioBuscado!=null){
                Usuario nuevo = new Usuario(usuario,campoContrasenaNueva.getText());
                ctrusu.crear(nuevo);
                JOptionPane.showMessageDialog(this,
                "Se creo con exito el nuevo usuario",
                "Exito",
                JOptionPane.INFORMATION_MESSAGE);
                super.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Ya existe el usuario en la base de datos",
                "Error!",
                JOptionPane.INFORMATION_MESSAGE);
                return;
        }*/
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaNuevoUsuario dialog = new VentanaNuevoUsuario(new javax.swing.JFrame(),true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContrasenaNueva;
    private javax.swing.JTextField campoUsuarioNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
