/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.cliente;



import javax.swing.JOptionPane;
import modelo.Cliente;
import controlador.ControladorCliente;
import controlador.ControladorCuentaCorriente;
import java.util.Date;
import modelo.CuentaCorriente;


/**
 *
 * @author Analía Santomé
 */
public class AltaCliente extends javax.swing.JDialog {
    ControladorCliente ctrcli = new ControladorCliente();
    ControladorCuentaCorriente ctrcuc = new ControladorCuentaCorriente();
    private Long numeroDocumento;
    private Integer numeroCalle,codigoPostal,piso;
    /**
     * Creates new form AltaProveedor
     */
    public AltaCliente() {
        
        initComponents();
        setLocationRelativeTo(null);
    }
    

    public void ingresoIncorrectoNumero (Integer valorCampo,String nombreCulpable,Long valorCampo2){
        
        try{
        //Integer piso = Integer.parseInt(campo.getText());
            if(valorCampo!=null && valorCampo<0 || valorCampo2!=null && valorCampo2<0){
               JOptionPane.showMessageDialog(this,
                       "Valor incorrecto para el campo '"+nombreCulpable+"'",
                       "Error!",
                        JOptionPane.INFORMATION_MESSAGE);
                        campoNumeroCalle.setText("");
                       
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,
                   "Solo se aceptan numeros enteros en el campo '"+nombreCulpable+"'",
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                    campoNumeroCalle.setText("");
                  
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        campoFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        campoNombreContacto = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        boxSexo = new javax.swing.JComboBox<>();
        etiquetaNumeroDocumento = new javax.swing.JLabel();
        campoNumeroDocumento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        boxDocumento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoMontoMaximo = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoNombreComercial = new javax.swing.JTextField();
        etiquetaCUIT = new javax.swing.JLabel();
        boxIVA = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        campoCUIT = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiquetaCodigoTelefonoCelular = new javax.swing.JLabel();
        campoCodigoAreaCelular = new javax.swing.JTextField();
        etiquetaNumeroCelular = new javax.swing.JLabel();
        campoNumeroCelular = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        etiquetaCodigoTelefonoFijo = new javax.swing.JLabel();
        campoCodigoAreaFijo = new javax.swing.JTextField();
        etiquetaNumeroFijo = new javax.swing.JLabel();
        campoNumeroFijo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoCalle = new javax.swing.JTextField();
        etiquetaNumeroCalle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoProvincia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoLocalidad = new javax.swing.JTextField();
        etiquetaPiso = new javax.swing.JLabel();
        campoPiso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoDepartamento = new javax.swing.JTextField();
        etiquetaCodigoPostal = new javax.swing.JLabel();
        campoCodigoPostal = new javax.swing.JTextField();
        campoNumeroCalle = new javax.swing.JFormattedTextField();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos generales"));

        jLabel2.setText("Nombre");

        jLabel3.setText("Sexo");

        jLabel14.setText("Email");

        boxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        etiquetaNumeroDocumento.setText("Numero");

        campoNumeroDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroDocumentoFocusLost(evt);
            }
        });

        jLabel4.setText("Tipo documento");

        boxDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DU (DNI)", "PAS", "LC", "LE" }));

        jLabel1.setText("Fecha de Nac.");

        jLabel6.setText("Monto maximo");

        campoMontoMaximo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMontoMaximoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(campoEmail))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiquetaNumeroDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumeroDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoMontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(boxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNumeroDocumento)
                    .addComponent(campoNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addComponent(campoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(campoMontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturacion"));

        jLabel5.setText("Nombre Comercial");

        campoNombreComercial.setEnabled(false);

        etiquetaCUIT.setText("CUIT/CUIL");

        boxIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable Inscripto", "Monotributista", "Consumidor final" }));
        boxIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIVAActionPerformed(evt);
            }
        });

        jLabel18.setText("Condicion IVA");

        try {
            campoCUIT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCUIT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCUIT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCUITFocusLost(evt);
            }
        });
        campoCUIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCUITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaCUIT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(boxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCUIT)
                    .addComponent(campoCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefonos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Celular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        etiquetaCodigoTelefonoCelular.setText("Cod. de Area");

        campoCodigoAreaCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoAreaCelularFocusLost(evt);
            }
        });

        etiquetaNumeroCelular.setText("Numero");

        campoNumeroCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCelularFocusLost(evt);
            }
        });
        campoNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCelularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaNumeroCelular)
                    .addComponent(etiquetaCodigoTelefonoCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(campoCodigoAreaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(campoNumeroCelular))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoTelefonoCelular)
                    .addComponent(campoCodigoAreaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumeroCelular)
                    .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fijo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        etiquetaCodigoTelefonoFijo.setText("Cod. de Area");

        campoCodigoAreaFijo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoAreaFijoFocusLost(evt);
            }
        });

        etiquetaNumeroFijo.setText("Numero");

        campoNumeroFijo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroFijoFocusLost(evt);
            }
        });
        campoNumeroFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroFijoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaNumeroFijo)
                    .addComponent(etiquetaCodigoTelefonoFijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campoCodigoAreaFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(campoNumeroFijo))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoTelefonoFijo)
                    .addComponent(campoCodigoAreaFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumeroFijo)
                    .addComponent(campoNumeroFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel7.setText("Calle");

        etiquetaNumeroCalle.setText("Numero");

        jLabel9.setText("Provincia");

        jLabel10.setText("Localidad");

        etiquetaPiso.setText("Piso");

        campoPiso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPisoFocusLost(evt);
            }
        });

        jLabel12.setText("Departamento");

        etiquetaCodigoPostal.setText("Codigo Postal");

        campoCodigoPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoPostalFocusLost(evt);
            }
        });

        campoNumeroCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCalleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(etiquetaNumeroCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaPiso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPiso))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(etiquetaCodigoPostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoCodigoPostal, campoDepartamento});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNumeroCalle)
                    .addComponent(etiquetaPiso)
                    .addComponent(campoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCodigoPostal)
                    .addComponent(campoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this,
                        "Desea salir sin guardar?",                       
                        "Atencion!",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.NO_OPTION){
                    
                }else{
                   super.dispose(); 
                }
    }//GEN-LAST:event_botonSalirActionPerformed
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Cliente nuevoCliente = new Cliente();
        
        if(campoNombreContacto.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Es necesario un nombre para el cliente",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        if(campoMontoMaximo.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Es necesario un monto maximo para la cuenta",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
        }
        nuevoCliente.setNombre(campoNombreContacto.getText());
        String sexo = (String)boxSexo.getSelectedItem();
        if(sexo!=null){
            nuevoCliente.setSexo(sexo.charAt(0));
        }
        if(!campoNumeroDocumento.getText().isEmpty()){
            nuevoCliente.setDni(Long.parseLong(campoNumeroDocumento.getText()));
        }
        nuevoCliente.setEmail(campoEmail.getText());
        nuevoCliente.setFechaNacimiento(campoFechaNacimiento.getDate());
        nuevoCliente.setCondicionIVA((String)boxIVA.getSelectedItem());
        
        if(boxIVA.getSelectedItem().equals("Responsable Inscripto") || boxIVA.getSelectedItem().equals("Monotributista") ){
            nuevoCliente.setCuit(Long.parseLong(campoCUIT.getText().replace("-", "")));
        }else{
            nuevoCliente.setCuil(Long.parseLong(campoCUIT.getText().replace("-", "")));
        }
        
        if(!campoCodigoAreaFijo.getText().isEmpty() && !campoNumeroFijo.getText().isEmpty()){
            nuevoCliente.setTelefono1(Long.parseLong(campoCodigoAreaFijo.getText()+campoNumeroFijo.getText()));
        }
        if(!campoCodigoAreaCelular.getText().isEmpty() && !campoNumeroCelular.getText().isEmpty()){
            nuevoCliente.setTelefono2(Long.parseLong(campoCodigoAreaCelular.getText()+campoNumeroCelular.getText()));
        }
        
        nuevoCliente.setCalle(campoCalle.getText());
        nuevoCliente.setCodigoPostal(codigoPostal);
        nuevoCliente.setCondicionIVA((String)boxIVA.getSelectedItem());
        nuevoCliente.setDepartamento(campoDepartamento.getText());
        if(!campoNumeroCalle.getText().isEmpty()){
            nuevoCliente.setNumeroCalle(Integer.parseInt(campoNumeroCalle.getText()));
        }
        if(!campoPiso.getText().isEmpty()){
            nuevoCliente.setPiso(Integer.parseInt(campoPiso.getText()));
        }
        nuevoCliente.setProvincia(campoProvincia.getText());
        nuevoCliente.setLocalidad(campoLocalidad.getText());
        nuevoCliente.setTipoDocumento((String)boxDocumento.getSelectedItem());
        CuentaCorriente nuevaCuenta = new CuentaCorriente();
        nuevaCuenta.setFecha_alta(new Date());
        nuevaCuenta.setMonto_acumulado(0.0);
        nuevaCuenta.setMonto_maximo(Double.parseDouble(campoMontoMaximo.getText()));
        
        try{
            ctrcuc.crear(nuevaCuenta);
            nuevoCliente.setCuentaCorriente(nuevaCuenta);
            ctrcli.crear(nuevoCliente);
            
            int respuesta=JOptionPane.showConfirmDialog(this,
                        "Se guardo correctamente el cliente" +
                        "¿Desea registrar otro?",
                        "Exito",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    limpiarCampos();
                        
                    }else{
                   super.dispose(); 
                }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

     public void limpiarCampos(){
        campoNombreContacto.setText("");
        campoNumeroDocumento.setText("");
        campoEmail.setText("");
        campoFechaNacimiento.cleanup();
        campoMontoMaximo.setText("");
        campoNombreComercial.setText("");
        campoNombreComercial.setEnabled(false);
        campoCUIT.setText("");
        campoCodigoAreaCelular.setText("");
        campoCodigoAreaFijo.setText("");
        campoNumeroCelular.setText("");
        campoNumeroFijo.setText("");
        campoCalle.setText("");
        campoNumeroCalle.setText("");
        campoCodigoPostal.setText("");
        campoDepartamento.setText("");
        campoLocalidad.setText("");
        campoPiso.setText("");
        campoProvincia.setText("");
    }
    
    private void campoCUITFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCUITFocusLost
        String numeroCUIT = campoCUIT.getText().replace("-", "");

        if(!numeroCUIT.isEmpty()){
            if(numeroCUIT.length()>11){
                JOptionPane.showMessageDialog(this,
                    "El numero de CUIT no puede superar los 11 digitos",
                    "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            try{
                ingresoIncorrectoNumero(null,"CUIT",Long.parseLong(numeroCUIT));
                
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaCUIT.getText());
            }

        }
    }//GEN-LAST:event_campoCUITFocusLost

    private void campoNumeroDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroDocumentoFocusLost
       String numeroDocumento = campoNumeroDocumento.getText();
        if(!numeroDocumento.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"Numero de documento",Long.parseLong(numeroDocumento));
                this.numeroDocumento = Long.parseLong(numeroDocumento);
            }catch(Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroDocumento.getText());
            }
        }
    }//GEN-LAST:event_campoNumeroDocumentoFocusLost

    private void campoNumeroCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCalleFocusLost
        String numeroCalle = campoNumeroCalle.getText();
        if(!numeroCalle.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroCalle),"Numero de la calle",null);
                this.numeroCalle = Integer.parseInt(numeroCalle);
            }catch(Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroCalle.getText());
            }
        }
    }//GEN-LAST:event_campoNumeroCalleFocusLost

    private void campoCodigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoPostalFocusLost
        String numeroCP = campoCodigoPostal.getText();
        if(!numeroCP.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroCP),"Codigo postal",null);
                codigoPostal = Integer.parseInt(numeroCP);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaCodigoPostal.getText());
            }
    }//GEN-LAST:event_campoCodigoPostalFocusLost
    }
    private void campoPisoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPisoFocusLost
        String numeroPiso = campoPiso.getText();
        if(!numeroPiso.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroPiso),"Piso",null);
                piso = Integer.parseInt(numeroPiso);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaPiso.getText());
            }
    }//GEN-LAST:event_campoPisoFocusLost
    }
    private void campoNumeroFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroFijoActionPerformed

    private void campoNumeroFijoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroFijoFocusLost
        String numeroFijo = campoNumeroFijo.getText();
        if(!numeroFijo.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroFijo),"Telefono fijo",null);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroFijo.getText());
            }
    }//GEN-LAST:event_campoNumeroFijoFocusLost
    }
    private void campoCodigoAreaFijoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoAreaFijoFocusLost
        String numeroCodigoAreaFijo = campoCodigoAreaFijo.getText();
        if(!numeroCodigoAreaFijo.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroCodigoAreaFijo),"Codigo de area (fijo)",null);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaCodigoTelefonoFijo.getText());
            }
    }//GEN-LAST:event_campoCodigoAreaFijoFocusLost
    }
    private void campoNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroCelularActionPerformed

    private void campoNumeroCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCelularFocusLost
        String numeroCelular = campoNumeroCelular.getText();
        if(!numeroCelular.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"Telefono celular",Long.parseLong(numeroCelular));
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroCelular.getText());
            }
    }//GEN-LAST:event_campoNumeroCelularFocusLost
    }
    private void campoCodigoAreaCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoAreaCelularFocusLost
        String numeroCodigoAreaCelular = campoCodigoAreaCelular.getText();
        if(!numeroCodigoAreaCelular.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"Codigo de area (celular)",Long.parseLong(numeroCodigoAreaCelular));

            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaCodigoTelefonoCelular.getText());
            }
    }//GEN-LAST:event_campoCodigoAreaCelularFocusLost
    }
    private void campoMontoMaximoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMontoMaximoFocusLost
        String montoMaximo = campoMontoMaximo.getText();
        if(!montoMaximo.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(montoMaximo),"Numero de documento",null);
                
            }catch(Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroDocumento.getText());
            }
        }
    }//GEN-LAST:event_campoMontoMaximoFocusLost

    private void boxIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIVAActionPerformed
        if(boxIVA.getSelectedItem().equals("Responsable Inscripto")){
            campoNombreComercial.setEnabled(true);
        }else{
            campoNombreComercial.setEnabled(false);
        }
    }//GEN-LAST:event_boxIVAActionPerformed

    private void campoCUITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCUITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCUITActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> boxDocumento;
    private javax.swing.JComboBox<String> boxIVA;
    private javax.swing.JComboBox<String> boxSexo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField campoCUIT;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCodigoAreaCelular;
    private javax.swing.JTextField campoCodigoAreaFijo;
    private javax.swing.JTextField campoCodigoPostal;
    private javax.swing.JTextField campoDepartamento;
    private javax.swing.JTextField campoEmail;
    private com.toedter.calendar.JDateChooser campoFechaNacimiento;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JTextField campoMontoMaximo;
    private javax.swing.JTextField campoNombreComercial;
    private javax.swing.JTextField campoNombreContacto;
    private javax.swing.JFormattedTextField campoNumeroCalle;
    private javax.swing.JTextField campoNumeroCelular;
    private javax.swing.JFormattedTextField campoNumeroDocumento;
    private javax.swing.JTextField campoNumeroFijo;
    private javax.swing.JTextField campoPiso;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.JLabel etiquetaCUIT;
    private javax.swing.JLabel etiquetaCodigoPostal;
    private javax.swing.JLabel etiquetaCodigoTelefonoCelular;
    private javax.swing.JLabel etiquetaCodigoTelefonoFijo;
    private javax.swing.JLabel etiquetaNumeroCalle;
    private javax.swing.JLabel etiquetaNumeroCelular;
    private javax.swing.JLabel etiquetaNumeroDocumento;
    private javax.swing.JLabel etiquetaNumeroFijo;
    private javax.swing.JLabel etiquetaPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    private void ingresoStringEnCampoNumerico(String nombreCampo) {
        JOptionPane.showMessageDialog(this,
                   "Solo se aceptan caracteres numericos en el campo "+nombreCampo,
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   
    }
   
    
    
    
}
