/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.cliente;

import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Recibo;
import modelo.SistemaVenta;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import soporte.NumeroALetra;

/**
 *
 * @author guti_
 */
public class GenerarCobro extends javax.swing.JDialog {

    SistemaVenta sv = SistemaVenta.getSistemaVenta();
    Recibo recibo = new Recibo();
    public JasperViewer visor;
    private float valorEfectivo;
    private float valorCheque;
    
    public GenerarCobro(java.awt.Frame parent, boolean modal, Recibo recibo) {
        super(parent, modal);
        initComponents();
        setTitle("Generar Recibo");
        setLocationRelativeTo(parent);
        this.recibo = recibo;
        completarCampos();
        bloquearCampos();
    }

    private void completarCampos(){
        float importeRecibido = sv.hayOtroRecibo(recibo.getFactura().getVenta());
        if(importeRecibido == 0){
            cajaImporteVenta.setText(String.valueOf(recibo.getFactura().getImporteTotal()));
        }
        cajaFechaFactura.setText(recibo.getFactura().getFechaEmision());
        cajaFechaVenta.setText(recibo.getFactura().getVenta().getFechaVenta());
        cajaImporteVenta.setText(String.valueOf(recibo.getFactura().getImporteTotal() - importeRecibido));
        cajaImporteEfectivo.setText("0.00");
    }
    
    private void bloquearCampos(){
        comboCheque.setSelected(false);
        cajaFechaVenta.setEnabled(false);
        cajaFechaFactura.setEnabled(false);
        cajaImporteVenta.setEnabled(false);
        cajaNroCheque.setEnabled(false);
        cajaImporteCheque.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cajaImporteEfectivo = new javax.swing.JTextField();
        comboCheque = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cajaNroCheque = new javax.swing.JTextField();
        cajaImporteCheque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Cobro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Efectivo");

        cajaImporteEfectivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaImporteEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaImporteEfectivoActionPerformed(evt);
            }
        });

        comboCheque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboCheque.setText("Cheque");
        comboCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboChequeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nro Cheque");

        cajaNroCheque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cajaImporteCheque.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaImporteCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaImporteChequeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Importe");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cajaImporteEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboCheque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(cajaNroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cajaImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaImporteEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(comboCheque)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cajaNroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(52, 52, 52)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAceptar, btnCancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAceptar, btnCancelar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaImporteChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaImporteChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaImporteChequeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboChequeActionPerformed
        if(comboCheque.isSelected()){
            cajaImporteCheque.setEnabled(true);
            cajaNroCheque.setEnabled(true);
        }else{
            cajaImporteCheque.setEnabled(false);
            cajaNroCheque.setEnabled(false);
        }
    }//GEN-LAST:event_comboChequeActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(agregarRecibo()){
            Recibo recibo2 = recibo;
            if(sv.hayOtroRecibo(recibo2.getFactura().getVenta()) + recibo2.getImporteTotalRecibo() 
                    >= recibo2.getFactura().getImporteTotal()){
                //recibo.getFactura().getVenta().setEstadoPago(true);
                recibo2.confirmarPago(recibo2.getFactura());
            }
            //recibo.getFactura().getVenta().getCliente().sumarImporte(recibo.getImporteCheque() + recibo.getImporteEfectivo());
            recibo2.sumarImporteCliente(recibo2.getImporteCheque() + recibo2.getImporteEfectivo());
            sv.addRecibo(recibo2);
            sv.guardarDatos();
            generarRecibo();
        }
            
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cajaImporteEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaImporteEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaImporteEfectivoActionPerformed

    private boolean agregarRecibo(){
        if(cajaImporteEfectivo.getText().trim().isEmpty() && cajaNroCheque.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar algún valor!", "Hubo un problema..", JOptionPane.WARNING_MESSAGE);
            return false;
        }else if(!comboCheque.isSelected()){
            valorEfectivo = Float.parseFloat(cajaImporteEfectivo.getText().trim());
            if(valorEfectivo > 0){
                recibo.setImporteEfectivo(valorEfectivo);
                recibo.setNroCheque("-");
                recibo.setImporteCheque(0.00f);
                return true;
            }else{
                JOptionPane.showMessageDialog(this, "Ingresó un valor nulo!", "Hubo un problema..", JOptionPane.WARNING_MESSAGE);
                return false;
            }  
        }else{
            valorEfectivo = Float.parseFloat(cajaImporteEfectivo.getText().trim());
            valorCheque = Float.parseFloat(cajaImporteCheque.getText().trim());
            if(!cajaNroCheque.getText().isEmpty() && valorCheque > 0){
                recibo.setImporteEfectivo(valorEfectivo);
                recibo.setImporteCheque(valorCheque);
                recibo.setNroCheque(cajaNroCheque.getText().trim());
                if(recibo.getNroCheque().isEmpty())
                    recibo.setNroCheque("-");
                return true;
            }else{
                JOptionPane.showMessageDialog(this, "Verifique los datos del cheque y los importes!", "Hubo un problema..", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
    }
    
    private void generarRecibo(){
        try {
            NumeroALetra numLetra = new NumeroALetra();
            DecimalFormat df = new DecimalFormat("0.00");
            String importe = String.valueOf(df.format(recibo.getImporteTotalRecibo()));
            JasperReport jr = (JasperReport)JRLoader.loadObject
            (this.getClass().getResource("/reporte/recibo.jasper"));
            //JasperReport jr = JasperCompileManager.compileReport(getClass()
            //        .getResource("/reporte/facturaA.jrxml").getPath());
            Map mapa = new HashMap();
            JasperPrint jp;
            mapa.put("domicilioEmpresa", sv.getDomicilio());
            mapa.put("nombreEmpresa", sv.getNombre());
            mapa.put("condicionIVAEmpresa", sv.getCondicionIva());
            mapa.put("puntoDeVentaEmpresa", String.format("%04d", sv.getPuntoVenta()));
            mapa.put("nroRecibo", String.format("%08d", recibo.getNroRecibo()));
            mapa.put("cuitEmpresa", sv.getCuit());
            mapa.put("fechaInicioActividades", sv.getFechaInicio());
            mapa.put("nombreEmpresaCliente", recibo.getFactura().getVenta().getCliente().getNombre());
            mapa.put("importeEnLetras", numLetra.Convertir(importe, false));
            mapa.put("fechaFactura", recibo.getFactura().getFechaEmision());
            mapa.put("nroFactura", String.format("0%08d", recibo.getFactura().getNroFactura()));
            mapa.put("importeFactura", String.valueOf(recibo.getFactura().getImporteTotal()));
            mapa.put("importeEfectivo", String.valueOf(recibo.getImporteEfectivo()));
            mapa.put("importeCheque", String.valueOf(recibo.getImporteCheque()));
            mapa.put("nroCheque", recibo.getNroCheque());
            mapa.put("importeTotal", String.valueOf(recibo.getImporteTotalRecibo()));
            
            jp = JasperFillManager.fillReport(jr, mapa, new JREmptyDataSource());
            visor = new JasperViewer(jp,false);
            visor.setVisible(true);
            this.dispose();
            visor.toFront();
        }catch (JRException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField cajaImporteCheque;
    private javax.swing.JTextField cajaImporteEfectivo;
    private javax.swing.JTextField cajaNroCheque;
    private javax.swing.JRadioButton comboCheque;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
