/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.AltaProveedor;


import controlador.ControladorProveedor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import modelo.Proveedor;

/**
 *
 * @author Analía Santomé
 */
public class AltaProveedor extends javax.swing.JDialog {
    ControladorProveedor ctrprov = new ControladorProveedor();
    DefaultListModel modeloLista = new DefaultListModel();
    Integer numeroCalle,piso,codigoPostal;
    Long cbu,cuit;
    List<String>BancosAPoblar= new ArrayList<>(Arrays.asList("ABN AMRO Bank", "Banco de Galicia", "Banco Nación", "Banco de la Provincia de Bs. As.", "Industrial and Commercial Bank of China S.A.", "Citibank S.A.", "BBVA Banco Francés", "The Bank of Tokyo-Mitsubishi", "Banco de Córdoba", "Banco Supervielle S.A.", "Banco Ciudad", "Banco Patagonia S.A.", "Banco Hipotecario S.A.", "Banco de San Juan S.A.", "Banco do Brasil S.A.", "Banco de Tucumán", "Banco Municipal de Rosario", "Banco Santander Río S.A.", "Banco del Chubut", "Banco de Santa Cruz S.A.", "Banco de La Pampa", "Banco de Corrientes S.A.", "Banco Provincia del Neuquén", "HSBC Bank Argentina S.A.", "Banco Credicoop", "Banco Itau Buen Ayre S.A.", "Banco Pcia. de Tierra del Fuego", "Banco Macro, Banco Comafi S.A.","Banco Finansur S.A.", "Nuevo Banco del Chaco S.A.", "MBA Banco De Inversiones S.A.", "Banco Formosa S.A.", "Banco CMF S.A.", "Nuevo Banco Industrial de Azul", "Deutsche Bank S.A.", "Nuevo Banco de Santa Fe", "Banco Santiago del Estero S.A.", "Banco Más Ventas", "Nuevo Banco de Entre Ríos S.A."));
    DefaultListModel <String> modeloSeleccionados = new DefaultListModel<String>();
    DefaultListModel <String> modeloDisponibles = new DefaultListModel<String>();
    
    
    
    
    
    
    /**
     * Creates new form AltaProveedor
     */
    public AltaProveedor(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        cargarBancos();
        setLocationRelativeTo(null);
        
    }
    private void cargarBancos(){
        for(String banco : BancosAPoblar){
            modeloDisponibles.addElement(banco);
            
        }
        listaBancosDisponibles.setModel(modeloDisponibles);
        
        
        
    }
    public void activarTransferencias(){
        if(!checkTransferencia.isSelected() && !checkDeposito.isSelected()){
            campoCBU.setEnabled(false);
            listaBancosDisponibles.setEnabled(false);
            listaBancosSeleccionados.setEnabled(false);
        }
        if(checkTransferencia.isSelected() && checkDeposito.isSelected()){
            campoCBU.setEnabled(true);
            listaBancosDisponibles.setEnabled(true);
            listaBancosSeleccionados.setEnabled(true);
        }
        if(!checkTransferencia.isSelected() && checkDeposito.isSelected()){
            campoCBU.setEnabled(true);
            listaBancosDisponibles.setEnabled(true);
            listaBancosSeleccionados.setEnabled(true);
        }
        if(checkTransferencia.isSelected() && !checkDeposito.isSelected()){
            campoCBU.setEnabled(true);
            listaBancosDisponibles.setEnabled(true);
            listaBancosSeleccionados.setEnabled(true);
        }
    }

    public void ingresoIncorrectoNumero (Integer valorCampo,String nombreCulpable,Long valorCampo2){
        
        try{
        //Integer piso = Integer.parseInt(campo.getText());
            if(valorCampo!=null && valorCampo<0 || valorCampo2!=null && valorCampo2<0){
               JOptionPane.showMessageDialog(this,
                       "Valor incorrecto para el campo '"+nombreCulpable+"'",
                       "Error!",
                        JOptionPane.INFORMATION_MESSAGE);
                       return;
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,
                   "Solo se aceptan numeros enteros en el campo '"+nombreCulpable+"'",
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   return;
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pestanaContacto = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombreComercial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoNombreContacto = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        etiquetaCodigoTelefonoCelular = new javax.swing.JLabel();
        campoCodigoAreaCelular = new javax.swing.JTextField();
        etiquetaNumeroCelular = new javax.swing.JLabel();
        campoNumeroCelular = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        etiquetaCodigoTelefonoFijo = new javax.swing.JLabel();
        campoCodigoAreaFijo = new javax.swing.JTextField();
        etiquetaNumeroFijo = new javax.swing.JLabel();
        campoNumeroFijo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoCalle = new javax.swing.JTextField();
        etiquetaNumeroCalle = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoProvincia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoLocalidad = new javax.swing.JTextField();
        etiquetaPiso = new javax.swing.JLabel();
        campoPiso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoDepartamento = new javax.swing.JTextField();
        etiquetaCodigoPostal = new javax.swing.JLabel();
        campoCodigoPostal = new javax.swing.JTextField();
        campoNumeroCalle = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        campoPaginaWeb = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        checkEfectivo = new javax.swing.JCheckBox();
        checkTransferencia = new javax.swing.JCheckBox();
        checkDeposito = new javax.swing.JCheckBox();
        checkTarjeta = new javax.swing.JCheckBox();
        checkCheque = new javax.swing.JCheckBox();
        etiquetaCBU = new javax.swing.JLabel();
        campoCBU = new javax.swing.JTextField();
        etiquetaCUIT = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        campoRubro = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaBancosDisponibles = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaBancosSeleccionados = new javax.swing.JList<>();
        boxIVA = new javax.swing.JComboBox<>();
        campoCUIT = new javax.swing.JFormattedTextField();
        botonSalir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre comercial");

        jLabel2.setText("Nombre de contacto");

        jLabel14.setText("Email");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefonos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Celular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        etiquetaCodigoTelefonoCelular.setText("Cod. de Area");

        campoCodigoAreaCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoAreaCelularFocusLost(evt);
            }
        });

        etiquetaNumeroCelular.setText("Numero");

        campoNumeroCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCelularFocusLost(evt);
            }
        });
        campoNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCelularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaNumeroCelular)
                    .addComponent(etiquetaCodigoTelefonoCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(campoCodigoAreaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(campoNumeroCelular))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoTelefonoCelular)
                    .addComponent(campoCodigoAreaCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumeroCelular)
                    .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fijo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        etiquetaCodigoTelefonoFijo.setText("Cod. de Area");

        campoCodigoAreaFijo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoAreaFijoFocusLost(evt);
            }
        });

        etiquetaNumeroFijo.setText("Numero");

        campoNumeroFijo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroFijoFocusLost(evt);
            }
        });
        campoNumeroFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroFijoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaNumeroFijo)
                    .addComponent(etiquetaCodigoTelefonoFijo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(campoCodigoAreaFijo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(campoNumeroFijo))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoTelefonoFijo)
                    .addComponent(campoCodigoAreaFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumeroFijo)
                    .addComponent(campoNumeroFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel7.setText("Calle");

        etiquetaNumeroCalle.setText("Numero");

        jLabel9.setText("Provincia");

        jLabel10.setText("Localidad");

        etiquetaPiso.setText("Piso");

        campoPiso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPisoFocusLost(evt);
            }
        });

        jLabel12.setText("Departamento");

        etiquetaCodigoPostal.setText("Codigo Postal");

        campoCodigoPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoPostalFocusLost(evt);
            }
        });

        campoNumeroCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCalleFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(etiquetaNumeroCalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etiquetaPiso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPiso))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(etiquetaCodigoPostal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoCodigoPostal, campoDepartamento});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNumeroCalle)
                    .addComponent(etiquetaPiso)
                    .addComponent(campoPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCodigoPostal)
                    .addComponent(campoCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setText("Pagina web");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(campoNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(campoPaginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pestanaContacto.addTab("Contacto", jPanel7);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formas de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        checkEfectivo.setText("Efectivo");

        checkTransferencia.setText("Transferencia");
        checkTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTransferenciaActionPerformed(evt);
            }
        });

        checkDeposito.setText("Deposito");
        checkDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDepositoActionPerformed(evt);
            }
        });

        checkTarjeta.setText("Tarjeta");

        checkCheque.setText("Cheque");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(checkEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTransferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDeposito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCheque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(checkEfectivo)
                .addComponent(checkTransferencia)
                .addComponent(checkDeposito)
                .addComponent(checkTarjeta)
                .addComponent(checkCheque))
        );

        etiquetaCBU.setText("CBU");

        campoCBU.setEnabled(false);
        campoCBU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCBUFocusLost(evt);
            }
        });

        etiquetaCUIT.setText("CUIT");

        jLabel18.setText("Condicion IVA");

        jLabel19.setText("Rubro");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bancos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Disponibles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        listaBancosDisponibles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaBancosDisponibles.setModel(new javax.swing.DefaultListModel<String>() {});
        listaBancosDisponibles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaBancosDisponibles.setEnabled(false);
        listaBancosDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaBancosDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaBancosDisponibles);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/flechas.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        listaBancosSeleccionados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listaBancosSeleccionados.setModel(new javax.swing.DefaultListModel<String>() {});
        listaBancosSeleccionados.setEnabled(false);
        listaBancosSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaBancosSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaBancosSeleccionados);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        boxIVA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable Inscripto\t", "Monotributista\t", "Exento" }));

        try {
            campoCUIT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCUIT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCUIT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCUITFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(etiquetaCBU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCBU, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(etiquetaCUIT))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCBU)
                    .addComponent(campoCBU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCUIT)
                    .addComponent(campoCUIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(campoRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pestanaContacto.addTab("Financiera", jPanel8);

        botonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pestanaContacto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pestanaContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroCelularActionPerformed

    private void campoNumeroFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroFijoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int respuesta=JOptionPane.showConfirmDialog(this,
                        "Desea salir sin guardar?",                       
                        "Atencion!",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.NO_OPTION){
                    return;
                }else{
                   super.dispose(); 
                }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void checkTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTransferenciaActionPerformed
        activarTransferencias();
        
    }//GEN-LAST:event_checkTransferenciaActionPerformed

    private void checkDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDepositoActionPerformed
       activarTransferencias();
        
    }//GEN-LAST:event_checkDepositoActionPerformed

    private void campoNumeroCalleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCalleFocusLost
        String numeroCalle = campoNumeroCalle.getText();
        if(!numeroCalle.isEmpty()){
            try{
            ingresoIncorrectoNumero(Integer.parseInt(numeroCalle),"Numero de la calle",null);
            this.numeroCalle = Integer.parseInt(numeroCalle);
            }catch(Exception e){
                ingresoStringEnCampoNumerico(etiquetaNumeroCalle.getText());
            }
        }
       
    }//GEN-LAST:event_campoNumeroCalleFocusLost

    private void campoPisoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPisoFocusLost
        String numeroPiso = campoPiso.getText();
        if(!numeroPiso.isEmpty()){
        try{
            ingresoIncorrectoNumero(Integer.parseInt(numeroPiso),"Piso",null);
            piso = Integer.parseInt(numeroPiso);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaPiso.getText());
                }
    }//GEN-LAST:event_campoPisoFocusLost
    }
    private void campoCodigoPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoPostalFocusLost
        String numeroCP = campoCodigoPostal.getText();
        if(!numeroCP.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroCP),"Codigo postal",null);
                codigoPostal = Integer.parseInt(numeroCP);
            }catch (Exception e){
                ingresoStringEnCampoNumerico(etiquetaCodigoPostal.getText());
            }
    }//GEN-LAST:event_campoCodigoPostalFocusLost
   }
    private void campoCodigoAreaFijoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoAreaFijoFocusLost
        String numeroCodigoAreaFijo = campoCodigoAreaFijo.getText();
        if(!numeroCodigoAreaFijo.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroCodigoAreaFijo),"Codigo de area (fijo)",null);
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaCodigoTelefonoFijo.getText());
                }
    }//GEN-LAST:event_campoCodigoAreaFijoFocusLost
    }
    private void campoNumeroFijoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroFijoFocusLost
        String numeroFijo = campoNumeroFijo.getText();
        if(!numeroFijo.isEmpty()){
            try{
                ingresoIncorrectoNumero(Integer.parseInt(numeroFijo),"Telefono fijo",null);
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaNumeroFijo.getText());
                }
    }//GEN-LAST:event_campoNumeroFijoFocusLost
    }
    private void campoCodigoAreaCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoAreaCelularFocusLost
        String numeroCodigoAreaCelular = campoCodigoAreaCelular.getText();
        if(!numeroCodigoAreaCelular.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"Codigo de area (celular)",Long.parseLong(numeroCodigoAreaCelular));
                
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaCodigoTelefonoCelular.getText());
                }
    }//GEN-LAST:event_campoCodigoAreaCelularFocusLost
    }
    private void campoNumeroCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCelularFocusLost
      String numeroCelular = campoNumeroCelular.getText();
        if(!numeroCelular.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"Telefono celular",Long.parseLong(numeroCelular));
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaNumeroCelular.getText());
                }
     
    }//GEN-LAST:event_campoNumeroCelularFocusLost
    }
    private void campoCBUFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCBUFocusLost
        String numeroCBU = campoCBU.getText();
        if(!numeroCBU.isEmpty()){
            try{
                ingresoIncorrectoNumero(null,"CBU",Long.parseLong(numeroCBU));
                cbu = Long.parseLong(numeroCBU);
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaCBU.getText());
                    
                }
     
    }
    }//GEN-LAST:event_campoCBUFocusLost

    private void campoCUITFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCUITFocusLost
        String numeroCUIT = campoCUIT.getText().replace("-", "");
        
        if(!numeroCUIT.isEmpty()){
            if(numeroCUIT.length()>11){
                JOptionPane.showMessageDialog(this,
                   "El numero de CUIT no puede superar los 11 digitos",
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   return;
            }
            try{
                ingresoIncorrectoNumero(null,"CUIT",Long.parseLong(numeroCUIT));
                cuit = Long.parseLong(numeroCUIT);;
                }catch (Exception e){
                    ingresoStringEnCampoNumerico(etiquetaCUIT.getText());
                }
     
    }
    }//GEN-LAST:event_campoCUITFocusLost

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        Proveedor prov = new Proveedor();
        
        //----CONTACTO----\\
        prov.setNombre_comercial(campoNombreComercial.getText());
        prov.setNombre_contacto(campoNombreContacto.getText());
        prov.setEmail(campoEmail.getText());
        prov.setPaginaWeb(campoPaginaWeb.getText());
        prov.setTelefono1(Long.parseLong(campoCodigoAreaFijo.getText()+campoNumeroFijo.getText()));
        prov.setTelefono2(Long.parseLong(campoCodigoAreaCelular.getText()+campoNumeroCelular.getText()));
        
        //----DIRECCION----\\
        prov.setCalle(campoCalle.getText());
        prov.setDepartamento(campoDepartamento.getText());
        prov.setProvincia(campoProvincia.getText());
        prov.setLocalidad(campoLocalidad.getText());
        prov.setNumero(this.numeroCalle);
        prov.setPiso(this.piso);
        prov.setCodigoPostal(this.codigoPostal);
        
        //----FINANCIERA----\\
        prov.setFormas_de_pago(getMediosDePago());
        
        prov.setCuit(cuit);
        prov.setCondicionIVA((String)boxIVA.getSelectedItem());
        prov.setRubro(campoRubro.getText());
        
        if(checkDeposito.isSelected() || checkTransferencia.isSelected()){
            prov.setCbu(cbu);
            prov.setBancos(getBancos());
        }
        
        try {
            ctrprov.crear(prov);
            int respuesta=JOptionPane.showConfirmDialog(this,
                        "Se guardo correctamente el proveedor" +
                        "¿Desea registrar otro?",
                        "Exito",
                        JOptionPane.YES_NO_OPTION);
                if(respuesta == JOptionPane.YES_OPTION){
                    limpiarCampos();
                    
                }else{
                   super.dispose(); 
                }
        } catch (Exception ex) {
            
        }
        
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void listaBancosDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaBancosDisponiblesMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()){
            String seleccionado = listaBancosDisponibles.getSelectedValue();
            //if(!modeloSeleccionados.contains(seleccionado)){
            modeloSeleccionados.addElement(seleccionado);
            listaBancosSeleccionados.setModel(modeloSeleccionados);
            //}
            modeloDisponibles.remove(listaBancosDisponibles.getSelectedIndex());
        }
    }//GEN-LAST:event_listaBancosDisponiblesMouseClicked

    private void listaBancosSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaBancosSeleccionadosMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()){
            String seleccionado = listaBancosSeleccionados.getSelectedValue();
            if(!modeloDisponibles.contains(seleccionado)){
                modeloDisponibles.addElement(seleccionado);
            }
            modeloSeleccionados.remove(listaBancosSeleccionados.getSelectedIndex());
        }
    }//GEN-LAST:event_listaBancosSeleccionadosMouseClicked
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaProveedor dialog = new AltaProveedor(new javax.swing.JFrame(), true);
                //new AltaProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> boxIVA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoCBU;
    private javax.swing.JFormattedTextField campoCUIT;
    private javax.swing.JTextField campoCalle;
    private javax.swing.JTextField campoCodigoAreaCelular;
    private javax.swing.JTextField campoCodigoAreaFijo;
    private javax.swing.JTextField campoCodigoPostal;
    private javax.swing.JTextField campoDepartamento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLocalidad;
    private javax.swing.JTextField campoNombreComercial;
    private javax.swing.JTextField campoNombreContacto;
    private javax.swing.JFormattedTextField campoNumeroCalle;
    private javax.swing.JTextField campoNumeroCelular;
    private javax.swing.JTextField campoNumeroFijo;
    private javax.swing.JTextField campoPaginaWeb;
    private javax.swing.JTextField campoPiso;
    private javax.swing.JTextField campoProvincia;
    private javax.swing.JTextField campoRubro;
    private javax.swing.JCheckBox checkCheque;
    private javax.swing.JCheckBox checkDeposito;
    private javax.swing.JCheckBox checkEfectivo;
    private javax.swing.JCheckBox checkTarjeta;
    private javax.swing.JCheckBox checkTransferencia;
    private javax.swing.JLabel etiquetaCBU;
    private javax.swing.JLabel etiquetaCUIT;
    private javax.swing.JLabel etiquetaCodigoPostal;
    private javax.swing.JLabel etiquetaCodigoTelefonoCelular;
    private javax.swing.JLabel etiquetaCodigoTelefonoFijo;
    private javax.swing.JLabel etiquetaNumeroCalle;
    private javax.swing.JLabel etiquetaNumeroCelular;
    private javax.swing.JLabel etiquetaNumeroFijo;
    private javax.swing.JLabel etiquetaPiso;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaBancosDisponibles;
    private javax.swing.JList<String> listaBancosSeleccionados;
    private javax.swing.JTabbedPane pestanaContacto;
    // End of variables declaration//GEN-END:variables

    private void ingresoStringEnCampoNumerico(String nombreCampo) {
        JOptionPane.showMessageDialog(this,
                   "Solo se aceptan caracteres numericos en el campo "+nombreCampo,
                   "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
                   return;
    }
    
    public List<String> getMediosDePago(){
        List<String> activados = new ArrayList<>();
        if(checkCheque.isSelected()){
            activados.add(checkCheque.getText());
        }
        if(checkDeposito.isSelected()){
            activados.add(checkDeposito.getText());
        }
        if(checkEfectivo.isSelected()){
            activados.add(checkEfectivo.getText());
        }
        if(checkTarjeta.isSelected()){
            activados.add(checkTarjeta.getText());
        }
        if(checkTransferencia.isSelected()){
            activados.add(checkTransferencia.getText());
        }
        return activados;
    }
    public List<String> getBancos(){
        
        Set<String> bancosSeleccionados = new HashSet<>();
        DefaultListModel modelo = (DefaultListModel) listaBancosSeleccionados.getModel();
        for(int i=0;i<modelo.size();i++){
            bancosSeleccionados.add((String)modelo.get(i));
        }
        List<String> bancosDevolver = new ArrayList<>(bancosSeleccionados);
        return bancosDevolver;
    }
    
    public void limpiarCampos(){
        campoCBU.setText("");
                    campoCUIT.setText("");
                    campoCalle.setText("");
                    campoCodigoAreaCelular.setText("");
                    campoCodigoAreaFijo.setText("");
                    campoCodigoPostal.setText("");
                    campoDepartamento.setText("");
                    campoEmail.setText("");
                    campoLocalidad.setText("");
                    campoNombreComercial.setText("");
                    campoNombreContacto.setText("");
                    campoNumeroCalle.setText("");
                    campoNumeroCelular.setText("");
                    campoNumeroFijo.setText("");
                    campoPaginaWeb.setText("");
                    campoPiso.setText("");
                    campoProvincia.setText("");
                    campoRubro.setText("");
                    checkCheque.setSelected(false);
                    checkDeposito.setSelected(false);
                    checkEfectivo.setSelected(false);
                    checkTarjeta.setSelected(false);
                    checkTransferencia.setSelected(false);
                    DefaultListModel modelo = (DefaultListModel) listaBancosSeleccionados.getModel();
                    modelo.clear();
    }
    
}
